const DEFAULT_MARGIN = 6;
const DEFAULT_GAP = 2;
const DEFAULT_MAX_SQUARE = 14;
const MIN_SQUARE = 6;
const MAX_SQUARE = 64;

const DEFAULT_WIDTH = 440;
const DEFAULT_HEIGHT = 140;
const MIN_WIDTH = 200;
const MAX_WIDTH = 1000;
const MIN_HEIGHT = 100;
const MAX_HEIGHT = 500;

const DEFAULT_BACKGROUND_RADIUS = 4;
const MIN_BACKGROUND_RADIUS = 0;
const MAX_BACKGROUND_RADIUS = 20;

const DEFAULT_CELL_RADIUS_FACTOR = 0.15;
const MIN_CELL_RADIUS_FACTOR = 0.0;
const MAX_CELL_RADIUS_FACTOR = 0.5;

const DEFAULT_CELL_BORDER_WIDTH = 0;
const MIN_CELL_BORDER_WIDTH = 0;
const MAX_CELL_BORDER_WIDTH = 5;

const UPDATE_INTERVALS = {
    HOURLY: 60 * 60 * 1000,
    DAILY: 24 * 60 * 60 * 1000,
    WEEKLY: 7 * 24 * 60 * 60 * 1000,
    MONTHLY: 30 * 24 * 60 * 60 * 1000
};

const ORIENTATIONS = {
    HORIZONTAL: "horizontal",
    VERTICAL: "vertical",
    VERTICAL_HEATMAP: "vertical-heatmap"
};
